version: '3.8'
services:
  web:
    image: php:8-apache
    container_name: php-apache-container
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    links:
      - mysql
    volumes:
      - .:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-availeble/000-default.conf

  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airslate
    volumes:
      - ./init.sql:/data/application/init.sql
